In [36]:
import pandas as pd
import numpy as np
imdb_df = pd.read_csv("./MovieData/movie_metadata 2.csv")

In [37]:
imdb_df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [38]:
imdb_df.keys()

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [39]:
imdb_df['title_year'].max()

2016.0

In [40]:
df_movie_imdb_link = imdb_df['movie_imdb_link']

In [41]:
movi_list = df_movie_imdb_link.to_list()

In [42]:
df_movie_imdb_link

0       http://www.imdb.com/title/tt0499549/?ref_=fn_t...
1       http://www.imdb.com/title/tt0449088/?ref_=fn_t...
2       http://www.imdb.com/title/tt2379713/?ref_=fn_t...
3       http://www.imdb.com/title/tt1345836/?ref_=fn_t...
4       http://www.imdb.com/title/tt5289954/?ref_=fn_t...
                              ...
5038    http://www.imdb.com/title/tt3000844/?ref_=fn_t...
5039    http://www.imdb.com/title/tt2071645/?ref_=fn_t...
5040    http://www.imdb.com/title/tt2107644/?ref_=fn_t...
5041    http://www.imdb.com/title/tt2070597/?ref_=fn_t...
5042    http://www.imdb.com/title/tt0378407/?ref_=fn_t...
Name: movie_imdb_link, Length: 5043, dtype: object

In [43]:
box_office = pd.read_csv("./MovieData/boxofficemojo_dataset/Mojo_budget_data.csv")

In [44]:
box_office.keys()

Index(['movie_id', 'movie_title', 'movie_year', 'director', 'writer',
       'producer', 'composer', 'cinematographer', 'main_actor_1',
       'main_actor_2', 'main_actor_3', 'main_actor_4', 'budget', 'domestic',
       'international', 'worldwide', 'mpaa', 'run_time', 'genre_1', 'genre_2',
       'genre_3', 'genre_4', 'link'],
      dtype='object')

In [45]:
imdb_df["movie_id"] = imdb_df.movie_imdb_link.str[26:35]

In [46]:
imdb_df["movie_id"].head()

0    tt0499549
1    tt0449088
2    tt2379713
3    tt1345836
4    tt5289954
Name: movie_id, dtype: object

In [47]:
merged_df = pd.merge(imdb_df, box_office, on='movie_id')

mask = merged_df.country.str.contains('USA')
merged_df = merged_df.drop(index=merged_df[~mask].index)

merged_df = merged_df.drop(['movie_id', 'movie_title_x', 'num_user_for_reviews', 'plot_keywords'], axis=1)
merged_df = merged_df.drop(['domestic', 'international'], axis=1)
merged_df = merged_df.drop(['gross', 'language'], axis=1)
merged_df = merged_df.drop(['imdb_score', 'color'], axis=1)
merged_df = merged_df.drop(['main_actor_2', 'main_actor_3', 'main_actor_1', 'facenumber_in_poster'], axis=1)
# removing duplicates and urelated attributes
merged_df = merged_df.drop(['run_time', 'budget_y', 'director_name', 'title_year', 'link', 'movie_imdb_link', 'genres', 'num_voted_users', 'movie_title_y', 'num_critic_for_reviews', 'content_rating', 'country', 'aspect_ratio'], axis=1)
merged_df.sort_values('movie_year')
# merged_df = merged_df.drop(['genre_4', 'genre_3'], axis=1)

,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,cast_total_facebook_likes,actor_3_name,budget_x,actor_2_facebook_likes,...,producer,composer,cinematographer,main_actor_4,worldwide,mpaa,genre_1,genre_2,genre_3,genre_4
1523,94.0,7.0,95.0,Amanda Detmer,3000.0,Alyson Hannigan,3451,Tsianina Joelson,16000000.0,240.0,...,Jay Cohen,Stewart Copeland,Ralf D. Bode,Gay Thomas Wilson,25850615,PG-13,Comedy,Drama,Romance,NaN
1510,94.0,480.0,486.0,Rachel Blanchard,1000.0,Ethan Suplee,3889,Paulo Costanzo,15600000.0,490.0,...,Daniel Goldberg,Michael Simpson,Mark Irwin,Paulo Costanzo,119754278,R,Comedy,NaN,NaN,NaN
459,124.0,258.0,748.0,Scott Glenn,867.0,Nicholas Lea,3424,Ben Mendelsohn,75000000.0,826.0,...,Martin Campbell,James Newton Howard,David Tattersall,Robin Tunney,215663859,PG-13,Action,Adventure,Drama,Thriller
842,116.0,0.0,71.0,Roger Jackson,287.0,Kelly Rutherford,600,Nancy O'Dell,40000000.0,157.0,...,Cathy Konrad,Marco Beltrami,Peter Deming,Liev Schreiber,161834276,R,Horror,Mystery,NaN,NaN
451,104.0,0.0,505.0,Tyler Mane,20000.0,Hugh Jackman,21397,Bruce Davison,75000000.0,764.0,...,Lauren Shuler Donner,Michael Kamen,Newton Thomas Sigel,Famke Janssen,296339528,PG-13,Action,Adventure,Sci-Fi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,123.0,452.0,329.0,Robin Atkin Downes,10000.0,Will Smith,11287,Ike Barinholtz,175000000.0,336.0,...,Charles Roven,Steven Price,Roman Vasyanov,Viola Davis,746846894,PG-13,Action,Adventure,Fantasy,Sci-Fi
1358,100.0,24.0,851.0,Jay Hernandez,15000.0,Mila Kunis,18786,Jada Pinkett Smith,20000000.0,1000.0,...,Bill Block,Christopher Lennertz,Jim Denault,Christina Applegate,183936074,R,Comedy,NaN,NaN,NaN
839,134.0,0.0,336.0,Frances O'Connor,1000.0,Javier Botet,2676,Robin Atkin Downes,40000000.0,575.0,...,Rob Cowan,Joseph Bishara,Don Burgess,Frances O'Connor,320392818,R,Horror,Mystery,Thriller,NaN
108,123.0,0.0,648.0,Callum Rennie,3000.0,Dominic Cooper,5505,Ruth Negga,160000000.0,716.0,...,Stuart Fenegan,Ramin Djawadi,Simon Duggan,Dominic Cooper,439048914,PG-13,Action,Adventure,Fantasy,NaN
341,141.0,335.0,635.0,Ayelet Zurer,11000.0,Morgan Freeman,13379,Moises Arias,NaN,745.0,...,Sean Daniel,Marco Beltrami,Oliver Wood,Nazanin Boniadi,94061311,PG-13,Action,Adventure,Drama,History

In [48]:
# inflation = 1.021
# for index, row in merged_df.iterrows():
#     power = 2016 - row['movie_year']
#     merged_df.at[index, 'budget_x'] = row['budget_x'] * (inflation ** power)
#     merged_df.at[index, 'worldwide'] = row['worldwide'] * (inflation ** power)
# merged_df = merged_df.drop('movie_year', axis=1)

In [49]:
# merged_df[['budget_x', 'movie_year']].head()

In [50]:
genre_1 = merged_df['genre_1'].unique()
genre_2 = merged_df['genre_2'].unique()
genre_3 = merged_df['genre_3'].unique()
genre_4 = merged_df['genre_4'].unique()


genres = np.concatenate((genre_1, genre_2, genre_3, genre_4), axis=0)

genres = genres[~pd.isna(genres)]
genres = np.unique(genres)

for g in genres:
    merged_df.insert(len(merged_df.columns), g, 0)

for item, row in merged_df.iterrows():
    for genre in genres:
        if genre == row['genre_1']:
            merged_df.at[item, genre] = 1
        if genre == row['genre_2']:
            merged_df.at[item, genre] = 1
        if genre == row['genre_3']:
            merged_df.at[item, genre] = 1
        if genre == row['genre_4']:
            merged_df.at[item, genre] = 1
merged_df = merged_df.drop(['genre_2', 'genre_1', 'genre_3', 'genre_4'], axis=1)

In [51]:
# actor_1 = merged_df['actor_1_name'].unique()
# actor_2 = merged_df['actor_2_name'].unique()
# actor_3 = merged_df['actor_3_name'].unique()
# actor_4 = merged_df['main_actor_4'].unique()


# actors = np.concatenate((actor_1, actor_2, actor_3, actor_4), axis=0)

# actors = actors[~pd.isna(actors)]
# actors = np.unique(actors)

# for a in actors:
#     merged_df.insert(len(merged_df.columns), a, 0)

# for item, row in merged_df.iterrows():
#     for actor in actors:
#         if actor == row['actor_1']:
#             merged_df.at[item, genre] = 1
#         if actor == row['actor_2']:
#             merged_df.at[item, genre] = 1
#         if actor == row['actor_3']:
#             merged_df.at[item, genre] = 1
#         if actor == row['actor_4']:
#             merged_df.at[item, genre] = 1
# merged_df = merged_df.drop(['actor_1_name', 'actor_2_name', 'actor_3_name', 'main_actor_4'], axis=1)

In [52]:
merged_df.head()

,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,cast_total_facebook_likes,actor_3_name,budget_x,actor_2_facebook_likes,...,Music,Musical,Mystery,News,Romance,Sci-Fi,Sport,Thriller,War,Western
0,178.0,0.0,855.0,Joel David Moore,1000.0,CCH Pounder,4834,Wes Studi,237000000.0,936.0,...,0,0,0,0,0,1,0,0,0,0
1,169.0,563.0,1000.0,Orlando Bloom,40000.0,Johnny Depp,48350,Jack Davenport,300000000.0,5000.0,...,0,0,0,0,0,0,0,0,0,0
3,164.0,22000.0,23000.0,Christian Bale,27000.0,Tom Hardy,106759,Joseph Gordon-Levitt,250000000.0,23000.0,...,0,0,0,0,0,0,0,0,0,0
4,132.0,475.0,530.0,Samantha Morton,640.0,Daryl Sabara,1873,Polly Walker,263700000.0,632.0,...,0,0,0,0,0,1,0,0,0,0
5,156.0,0.0,4000.0,James Franco,24000.0,J.K. Simmons,46055,Kirsten Dunst,258000000.0,11000.0,...,0,0,0,0,0,1,0,0,0,0

In [53]:
def normalize(df, feature):
    print(df[feature].mean())
    df[feature] = (df[feature]-df[feature].mean())/df[feature].std()
    # return df[feature].mean(), df[feature].std()
normalize(merged_df, 'cast_total_facebook_likes')
normalize(merged_df, 'actor_1_facebook_likes')
normalize(merged_df, 'budget_x')
normalize(merged_df, 'actor_2_facebook_likes')
normalize(merged_df, 'movie_facebook_likes')
normalize(merged_df, 'director_facebook_likes')
normalize(merged_df, 'actor_3_facebook_likes')
normalize(merged_df, 'duration')
normalize(merged_df, 'movie_year')

14561.372537313433
9517.976119402985
53758484.416262135
2719.4805970149255
13765.239402985075
872.2531343283582
1072.7671641791044
109.71283582089552
2007.5880597014925

In [54]:
merged_df.head()

,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,cast_total_facebook_likes,actor_3_name,budget_x,actor_2_facebook_likes,...,Music,Musical,Mystery,News,Romance,Sci-Fi,Sport,Thriller,War,Western
0,3.415162,-0.262591,-0.087463,Joel David Moore,-0.438793,CCH Pounder,-0.407342,Wes Studi,3.644265,-0.312258,...,0,0,0,0,0,1,0,0,0,0
1,2.965056,-0.093100,-0.029226,Orlando Bloom,1.570244,Johnny Depp,1.414928,Jack Davenport,4.897195,0.399282,...,0,0,0,0,0,0,0,0,0,0
3,2.714997,6.360482,8.806735,Christian Bale,0.900565,Tom Hardy,3.860857,Joseph Gordon-Levitt,3.902806,3.550788,...,0,0,0,0,0,0,0,0,0,0
4,1.114621,-0.119593,-0.217994,Samantha Morton,-0.457338,Daryl Sabara,-0.531337,Polly Walker,4.175269,-0.365484,...,0,0,0,0,0,1,0,0,0,0
5,2.314903,-0.262591,1.175678,James Franco,0.746024,J.K. Simmons,1.318823,Kirsten Dunst,4.061908,1.449784,...,0,0,0,0,0,1,0,0,0,0

In [55]:
mean, std = merged_df['worldwide'].mean(), merged_df['worldwide'].std()
normalize(merged_df, 'worldwide')

159729517.1755224

In [56]:
# import seaborn as sns
# sns.heatmap(merged_df.corr(), cmap='YlGnBu', annot=True, linewidths = 0.2);

In [57]:
from sklearn import preprocessing
def to_categorical(df, feature):
    le = preprocessing.LabelEncoder()
    le.fit(df[feature].unique())
    feature_cat = le.transform(df[feature])
    df.drop([feature], axis=1)
    df[feature] = feature_cat
    # return df

In [58]:
def one_hot_encode(df, column):
    """
    One hot encodes a column in a pandas DataFrame.
    
    Args:
        df (pandas.DataFrame): The DataFrame to one hot encode.
        column (str): The name of the column to one hot encode.
        
    Returns:
        pandas.DataFrame: The one hot encoded DataFrame.
    """
    # Get the unique values in the column
    unique_values = df[column].unique()
    
    # Create a new DataFrame with one hot encoded columns
    one_hot_df = pd.get_dummies(df[column], prefix=column)
    
    # Add the new columns to the original DataFrame
    df = pd.concat([df, one_hot_df], axis=1)
    
    # Drop the original column from the DataFrame
    df.drop(column, axis=1, inplace=True)
    
    return df

In [59]:
def de_normalize(y, mean, std):
    y = (y * std) + mean
    return y

In [60]:
to_categorical(merged_df, 'director')
to_categorical(merged_df, 'writer')
to_categorical(merged_df, 'producer')
to_categorical(merged_df, 'composer')
to_categorical(merged_df, 'cinematographer')
to_categorical(merged_df, 'main_actor_4')
to_categorical(merged_df, 'actor_2_name')
to_categorical(merged_df, 'actor_1_name')
to_categorical(merged_df, 'actor_3_name')
merged_df = one_hot_encode(merged_df, 'mpaa')
# to_categorical(merged_df, 'mpaa')
# to_categorical(merged_df, 'color')
# to_categorical(merged_df, 'language')

In [61]:
merged_df.dropna(inplace=True)

In [62]:

x = merged_df.loc[:, merged_df.columns != 'worldwide']
y = merged_df['worldwide']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)
x_train, x_test, y_train, y_test = x.head(int(len(x) * 0.7)), x.tail(int(len(x) * 0.3)), y.head(int(len(y) * 0.7)), y.tail(int(len(y) * 0.3))
mlr = LinearRegression()  
mlr.fit(x_train, y_train)

#Prediction of test set
y_pred_mlr= mlr.predict(x_test)
y_pred_mlr = de_normalize(y_pred_mlr, mean, std)
y_test = de_normalize(y_test, mean, std)
#Predicted values
# print("Prediction for test set: {}".format(y_pred_mlr))

from sklearn import metrics
meanAbErr = metrics.mean_absolute_error(y_test, y_pred_mlr)
meanSqErr = metrics.mean_squared_error(y_test, y_pred_mlr)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred_mlr))
print('R squared: {:.2f}'.format(mlr.score(x,y)*100))
print('Mean Absolute Error:', meanAbErr / 1000000)
print('Mean Square Error:', meanSqErr / 1000000)
print('Root Mean Square Error:', rootMeanSqErr / 1000000)

mlr_diff = pd.DataFrame({'Actual value': y_test, 'Predicted value': y_pred_mlr})
print(mlr_diff.head())

R squared: 62.08
Mean Absolute Error: 53.35160579761489
Mean Square Error: 5311677383.516609
Root Mean Square Error: 72.88125536457649
      Actual value  Predicted value
1356    66899242.0     2.958347e+07
1357   183936074.0     6.279686e+07
1358   183936074.0     6.279686e+07
1359    85749034.0     5.963568e+07
1360   115121981.0     1.767486e+08

In [73]:
from sklearn.preprocessing import PolynomialFeatures
x_train, x_test, y_train, y_test = x.head(int(len(x) * 0.7)), x.tail(int(len(x) * 0.3)), y.head(int(len(y) * 0.7)), y.tail(int(len(y) * 0.3))
poly_reg = PolynomialFeatures(degree=2)
X_poly = poly_reg.fit_transform(x_train)
pol_reg = LinearRegression()
pol_reg.fit(X_poly, y_train)

y_pred = pol_reg.predict(poly_reg.fit_transform(x_test))
y_pred = de_normalize(y_pred, mean, std)
y_test = de_normalize(y_test, mean, std)
meanAbErr = metrics.mean_absolute_error(y_test, y_pred)
meanSqErr = metrics.mean_squared_error(y_test, y_pred)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print('R squared: {:.2f}'.format(mlr.score(x,y)*100))
print('Mean Absolute Error:', meanAbErr / 1000000)
print('Mean Square Error:', meanSqErr / 1000000)
print('Root Mean Square Error:', rootMeanSqErr / 1000000)

mlr_diff = pd.DataFrame({'Actual value': y_test, 'Predicted value': y_pred})
print(mlr_diff.head())

R squared: 62.08
Mean Absolute Error: 618.1706937930505
Mean Square Error: 2034243761398.0984
Root Mean Square Error: 1426.2691756460624
      Actual value  Predicted value
1356    66899242.0     7.827608e+06
1357   183936074.0     5.601566e+08
1358   183936074.0     5.601566e+08
1359    85749034.0     5.755415e+08
1360   115121981.0    -2.140748e+09

In [29]:
import numpy as np
from sklearn.svm import SVR
import matplotlib.pyplot as plt
svr_lin = SVR(kernel="linear")

In [30]:
from sklearn.svm import LinearSVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression

In [36]:
x_train, x_test, y_train, y_test = x.head(int(len(x) * 0.7)), x.tail(int(len(x) * 0.3)), y.head(int(len(y) * 0.7)), y.tail(int(len(y) * 0.3))
regr = make_pipeline(StandardScaler(), LinearSVR(random_state=0, tol=1e-5))
regr.fit(x_train, y_train)
# Pipeline(steps=[('standardscaler', StandardScaler()),
                # ('linearsvr', LinearSVR(random_state=0, tol=1e-05))])

/Users/minasmacbook/opt/anaconda3/envs/torch/lib/python3.9/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvr', LinearSVR(random_state=0, tol=1e-05))])

In [37]:
y_pred = regr.predict(x_test)
print(y_pred)

[-0.63443322 -0.42599164 -0.42599164 -0.53660976  0.06798303 -0.19716455
 -0.6510625  -0.72180584 -0.18079502 -0.51997837 -0.64870103 -0.41230042
 -0.66556669 -0.42251319 -0.58363157 -0.6096441  -0.39697365 -0.45542113
 -0.54513663 -0.67862814 -0.36691747 -0.40675951 -0.64911008 -0.2512422
 -0.60782625 -0.60700414 -0.53862654 -0.77868822 -0.34772902 -0.6066275
 -0.52090765 -0.39398456 -0.08381691 -0.13753581 -0.67385479 -0.5181996
 -0.50145034 -0.73461081 -0.48319344 -0.55100863 -0.50412907 -0.30531813
 -0.70251339 -0.61519637 -0.73669975 -0.80731817 -0.46738229 -0.54501584
 -0.59847287 -0.39046003 -0.61800461 -0.59719363 -0.71323007 -0.77173236
 -0.53212721 -0.40279681 -0.60444453 -0.7518547  -0.76861837 -0.77580668
 -0.46028749 -0.46348455 -0.47390871 -0.75131888 -0.4883239  -0.58188755
 -0.49619217 -0.58337582 -0.37135034 -0.53447933 -0.47559877 -0.44117959
 -0.57694417 -0.50796933 -0.57247795 -0.53888999 -0.53888999 -0.64329088
 -0.56376573 -0.57827476 -0.47205256 -0.4696816  -0.42311126 -0.67786862
  0.12498672 -0.71986955 -0.50268773 -0.50006326 -0.79705163 -0.68875511
 -0.71430354 -0.25907242 -0.341844   -0.53990129 -0.6906793  -0.67986987
 -0.54921064 -0.6873993  -0.58679535 -0.6751365  -0.66635631 -0.3383371
 -0.4829924  -0.63788368 -0.40784698 -0.56178405 -0.72927296 -0.66435868
 -0.56755205 -0.69485867 -0.49725939 -0.45668907 -0.24374105 -0.5412042
 -0.47300701 -0.63470504 -0.19555163 -0.35813009 -0.67157677 -0.67157677
 -0.57875796 -0.61610593 -0.4172496  -0.70774703 -0.70774703 -0.10914775
 -0.50964062 -0.5423635  -0.32273491 -0.66011966 -0.7294328  -0.63409322
 -0.64822926 -0.65295059 -0.55669765 -0.60221696 -0.45917622 -0.51238846
 -0.67508034 -0.65526896 -0.52302868 -0.59211461 -0.46039449 -0.56930045
 -0.45272306 -0.45272306 -0.37055299 -0.65872039 -0.41906084 -0.5672632
 -0.59633017 -0.50981414 -0.60541085 -0.49741132 -0.49741132 -0.62094411
 -0.50462876 -0.10081268 -0.78466638 -0.55380551 -0.5897812  -0.67602977
 -0.74733352 -0.5600483  -0.57042551 -0.54360224 -0.71766527 -0.39267554
 -0.6595958  -0.62599112 -0.48364553 -0.69797975 -0.27604739 -0.66929516
 -0.56762713 -0.5658661  -0.39956109 -0.63840476 -0.42148101 -0.5662748
 -0.61363741 -0.78480144 -0.65625073 -0.46338791 -0.4236386  -0.58147022
 -0.29329798 -0.61087694 -0.5674464  -0.26782182 -0.5161034  -0.56148895
 -0.43573487 -0.64706259 -0.57828112 -0.65231372 -0.6851279  -0.56820971
 -0.60817969 -0.49712336 -0.56479829 -0.53366043 -0.62992548 -0.67158547
 -0.51806396 -0.58772369 -0.70632005  0.64729801  0.20995126 -0.53634668
 -0.53627751 -0.68171769 -0.52544584 -0.79650953 -0.51035671 -0.49445076
 -0.54923866 -0.8905078  -0.37851368 -0.62415394 -0.64641655 -0.62913577
 -0.69085761 -0.54717022 -0.74239075 -0.84994185 -0.66229237 -0.46052624
 -0.61584325 -0.77015345 -0.55765965 -0.60862217 -0.8050053  -0.31934423
 -0.52215428 -0.60778403 -0.72497372 -0.66766344 -0.60254443 -0.54350133
 -0.71048143 -0.71048143 -0.63497206 -0.62102599 -0.48970495 -0.49972111
 -0.65126949  0.05878365  0.02852039 -0.73263951 -0.60149762 -0.77908636
 -0.56722572 -0.39914287 -0.80777785 -0.61647169 -0.52594555 -0.78542288
 -0.66082625 -0.48686196 -0.81942184 -0.78116373 -0.84654553 -0.49381183
 -0.60261907 -0.33544667 -0.38348607 -0.59520718 -0.56298386 -0.59482145
 -0.6589158  -0.54328722 -0.45889773 -0.56919042 -0.70565581 -0.72619831
 -0.62386446 -0.58478809 -0.59410962 -0.64416686 -0.68025859 -0.45067896
  0.0918789  -0.50972586 -0.73093156 -0.74782453 -0.66946785 -0.54516862
 -0.30549426 -0.63123144 -0.42105304 -0.59871376 -0.61676174 -0.33352568
 -0.61544617 -0.61362561 -0.64497254  0.1597934  -0.29496802 -0.61932518
 -0.70001748 -0.70001748 -0.82098161 -0.3607972  -0.74600647 -0.30708651
 -0.66688844 -0.69423049 -0.50894168 -0.75136844 -0.63911287 -0.67979691
 -0.7927485  -0.58483561 -0.72852445 -0.60874838 -0.73980644 -0.46956822
 -0.60333224  0.0130547  -0.60198749 -0.72720629 -0.62720299 -0.3520732
 -0.67788126 -0.81635698 -0.77299413 -0.80700773 -0.55809531  0.10948783
 -0.80401562 -0.6956427  -0.66747898 -0.44690928 -0.36871012 -0.68510732
 -0.61530934 -0.60041432 -0.72702206 -0.58457573 -0.68581547 -0.6201744
 -0.77745876 -0.66603158 -0.7166834  -0.71768114 -0.7037744  -0.7986636
 -0.78592713 -0.58580192 -0.76409451 -0.6469716  -0.6453053  -0.6453053
 -0.23034032 -0.10744132 -0.66141912 -0.74584511 -0.64499896 -0.89561652
 -0.71060985 -0.56738976 -0.69634301 -0.59136166 -0.72856591 -0.69878703
 -0.87972527 -0.88426804 -0.77944086 -0.80711317 -0.56515743 -0.65221403
 -0.39750582 -0.85195392 -0.72604824 -0.9154066  -0.67249496 -0.80622282
 -0.54391331 -0.46701257 -0.78247286 -0.62803152 -0.804291   -0.84551681
 -0.75361144 -0.36872829 -0.53290213 -0.91868061 -0.4172491  -0.64040832
 -0.02959207 -0.9438187  -0.56649619 -0.49827348 -0.57608651 -0.72151591
 -0.67876319 -0.21933788 -0.85014968 -0.0979846  -0.55242248 -0.66295541
 -0.76010463 -0.425339   -0.80175755 -0.68305985 -0.79314339 -0.79897376
 -0.33962697 -0.77295446 -0.70516268 -0.82198337 -0.79794961 -0.88662977
 -0.52723862 -0.69609717 -0.73134235 -0.62009738 -0.74426182 -0.47665874
 -0.89453946 -0.61089097 -0.78211179 -0.70663434 -0.71941615 -0.02405078
 -0.67520721 -0.76520029 -0.74370832  0.07703635 -0.73690743 -0.57580897
 -0.61314232  0.20858881 -0.83213361 -0.75055425 -0.60095563 -0.50850221
 -0.27632856  0.10190704 -0.60030412 -0.69965398 -0.75661805 -0.72450972
  0.0399461  -0.70244432 -0.77742371 -0.81946154  0.04472526 -0.75105877
 -0.76756471 -0.73772326 -0.81318057 -0.75046654 -0.65466768 -0.08415351
  0.06616626 -0.65800331 -0.59160965 -0.83086169 -0.88637876 -0.22119466
 -0.77567659 -0.77185019 -0.7548258  -0.78320487 -0.51766517 -0.8115925
 -0.55864756 -0.7949929  -0.64785602 -0.65624747 -0.58125837 -0.69687728
 -0.83156374 -0.67277062 -0.67758261 -0.65762095 -1.00726702 -0.94370416
 -0.8129995  -0.67256044 -0.68483858  0.02006419 -0.4030467  -0.79474311
 -0.88590771 -0.73221958 -0.84007199 -1.00823345 -0.86987318 -0.1661194
 -0.68386548 -0.00436049]

In [38]:
y_pred = de_normalize(y_pred, mean, std)
y_test = de_normalize(y_test, mean, std)
meanAbErr = metrics.mean_absolute_error(y_test, y_pred)
meanSqErr = metrics.mean_squared_error(y_test, y_pred)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print('R squared: {:.2f}'.format(regr.score(x,y)*100))
print('Mean Absolute Error:', meanAbErr / 1000000)
print('Mean Square Error:', meanSqErr / 1000000)
print('Root Mean Square Error:', rootMeanSqErr)

mlr_diff = pd.DataFrame({'Actual value': y_test, 'Predicted value': y_pred})
print(mlr_diff.head())

R squared: 58.00
Mean Absolute Error: 41.895284632396546
Mean Square Error: 3758003862.0705767
Root Mean Square Error: 61302559.996060334
      Actual value  Predicted value
1356    66899242.0     2.213877e+07
1357   183936074.0     6.734389e+07
1358   183936074.0     6.734389e+07
1359    85749034.0     4.335393e+07
1360   115121981.0     1.744731e+08

In [40]:
mean / 1000000

159.72951717552237

In [41]:
std

216871914.11672443

In [ ]:
import numpy as np
from sklearn.svm import SVR
import matplotlib.pyplot as plt
svr_poly = SVR(kernel="poly", C=100, gamma="auto", degree=3, epsilon=0.1, coef0=1)

# svr_poly = SVR(kernel="poly", C=100, gamma="auto", degree=3, epsilon=0.1, coef0=1)
svr_poly.fit(x_train, y_train)
y_pred = svr_poly.predict(x_test)
#Predicted values
print("Prediction for test set: {}".format(y_pred))

from sklearn import metrics
meanAbErr = metrics.mean_absolute_error(y_test, y_pred)
meanSqErr = metrics.mean_squared_error(y_test, y_pred)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print('R squared: {:.2f}'.format(svr_poly.score(x,y)*100))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

mlr_diff = pd.DataFrame({'Actual value': y_test, 'Predicted value': y_pred})
print(mlr_diff.tail())